
#
# Usage: 
# ansible-playbook -l yl-n2-1701-dp ~/dbc/edge-ops/ansible/edge-setup.yml
#
#

---
- name: Edge Setup setup
  hosts: all
  vars:
    EID: /opt/apigee-install
    LOGFILE: "{{ EID }}/apigee-setup-{{lookup('pipe','date -u +\"%Y-%m-%dT%H:%M:%SZ\"')}}.log"

  environment: 
    EID: "{{ EID }}"   # Edge Install Directory
    
  tasks:
  - block:
      - local_action:
          module: command xmllint --xpath "//profile[id='edge-repo']/properties/username/text()" ~/.m2/settings.xml
        register: settings_username
      - local_action:
          module: command xmllint --xpath "//profile[id='edge-repo']/properties/password/text()" ~/.m2/settings.xml
        register: settings_password
      - set_fact:
          REPO_USERNAME: "{{settings_username.stdout}}"
          REPO_PASSWORD: "{{settings_password.stdout}}"

  - block: 
     - file: path="{{ EID }}" state=directory

     - get_url:
         url: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm"
         dest: "{{ EID }}"
         timeout: 180
     - yum:
         name: "{{ EID }}/epel-release-latest-7.noarch.rpm"
         state: present
     - get_url:
         url: "https://software.apigee.com/bootstrap_4.17.01.sh"
         dest: "{{ EID }}"
         url_username: "{{ REPO_USERNAME }}"
         url_password: "{{ REPO_PASSWORD }}"
         timeout: 180
     - shell: "bash {{EID}}/bootstrap_4.17.01.sh apigeeuser={{ REPO_USERNAME }} apigeepassword={{ REPO_PASSWORD }} apigeerepohost=software.apigee.com > {{ LOGFILE }}"
       args:
         chdir: "{{ EID }}/"

     - shell: "/opt/apigee/apigee-service/bin/apigee-service apigee-setup install >> {{ LOGFILE }}"
       args:
         chdir: "{{ EID }}/"

    become: yes
    become_method: sudo
